name: Kingdoms
author: Hex_27
version: maven-version
softdepend: [WorldGuard, WorldEdit]
description: Conquer lands with a mighty Kingdom!
main: me.leothepro555.kingdoms.Kingdoms
commands:
   k:
    description: opens help
   kingdom:
    description: opens help
   kingdoms:
    description: opens help